# Generated by Django 4.0.6 on 2022-09-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('langue', models.CharField(max_length=100)),
                ('nombredepage', models.IntegerField()),
                ('pays', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier', models.FileField(upload_to='')),
            ],
        ),
    ]
