# Generated by Django 4.0.6 on 2022-09-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='Titre',
            new_name='titre',
        ),
    ]
